### ISSUE TITLE
Make sub-items/nested lists work

### ISSUE THREAD

**Issue by jloeser** [hunyadi/md2conf#12]
Unfortunately, sub-items/nested lists (https://commonmark.org/help/tutorial/10-nestedLists.html) are not working properly:
```
$ head -n11 testing.md
<!-- confluence-page-id: 367198209 -->
<!-- confluence-space-key: ~62dfb0d2b6b0b70770d7d76c -->

* Foo
* Bar
  * foo
    * foo1
    * bar1
  * bar
    * foo2
    * bar2
```

This results in a one-level list in Confluence. I am wondering if would be possible to implement this feature?

**Comment by hunyadi** [comment]
You need to indent nested list items with four spaces instead of only two. You can even mix ordered lists and unordered lists in this manner. A nested list example has been added to the sample document.
