### ISSUE TITLE
Is it possible to create under a certain page instead of the root space? 

### ISSUE THREAD

**Issue by albertocarrf** [hunyadi/md2conf#13]
I don't know if it's not possible yet or I'm missing something, thanks for the great work!

**Comment by hunyadi** [comment]
Technically, `md2conf` does not *create* the Confluence wiki pages at the moment. You are responsible for creating the pages in advance, at whatever level of nesting you desire. Once the page has been created, you need to establish a binding between the Confluence page and the Markdown file, this is done with the *confluence-page-id* tag:

```
<!-- confluence-page-id: 85008200016 -->
```

In particular, we are synchronizing pages scattered around the Confluence space from a set of Markdown files in the same documentation directory.
