### ISSUE TITLE
Conversion is not working properly

### ISSUE THREAD

**Issue by albertocarrf** [hunyadi/md2conf#14]
I'm trying to publish a markdown file and the format and the style is really bad, am I doing something wrong?

Neither the text or the code block is showed properly:
<img width="919" alt="Captura de pantalla 2023-08-29 a las 17 03 40" src="https://github.com/hunyadi/md2conf/assets/102521188/1c5018d4-b5ce-4079-8f09-7ae0e17c3ea6">
<img width="898" alt="Captura de pantalla 2023-08-29 a las 17 05 59" src="https://github.com/hunyadi/md2conf/assets/102521188/156934c7-3b4a-4fee-a85b-d0a5e104558d">

**Comment by albertocarrf** [comment]
Hey, I tried removing everything but a couple of lines and I can't make it work it seems the parser introduces a lot of new lines and spaces that shouldn't be there:

![Captura de pantalla 2023-08-30 a las 9 45 28](https://github.com/hunyadi/md2conf/assets/102521188/d300ee56-5fb1-4417-a8c7-755d04b2cc7a)

![Captura de pantalla 2023-08-30 a las 9 45 46](https://github.com/hunyadi/md2conf/assets/102521188/2fb962d3-6608-48c2-a0ff-a1298b83f0e6)

![Captura de pantalla 2023-08-30 a las 9 46 35](https://github.com/hunyadi/md2conf/assets/102521188/51659c65-e3f8-4071-a3bb-6f01ced5d730)


This is the library version I'm using
Markdown           3.4.4

**Comment by hunyadi** [comment]
I have extended `sample/example.md` with additional examples:

```
An ordered list:

1. *List item 1*
2. **List item 2**
spanning multiple text file lines but rendered as a single line
3. _List item 3_
4. `List item 4`

A bullet point list:

* *List item 1*
* **List item 2**
spanning multiple text file lines but rendered as a single line
* _List item 3_
* `List item 4`

An unordered list:

- *List item 1*
- **List item 2**
spanning multiple text file lines but rendered as a single line
- _List item 3_
- `List item 4`
```

All of these work as expected in Confluence.

However, your example has the following snippet, which not all Markdown implementations allow because technically you can't make a monospace text bold (and the bold instruction is being ignored in all the sample output you shared).

```
**`user_id`**
```

Can you try a simpler version, e.g.

```
- `user_id` *(string)*: Id of the user.
```

Likewise, can you share an example that works (cutting down on all formatting instructions), and another that barely does not?

**Comment by albertocarrf** [comment]
![Captura de pantalla 2023-08-30 a las 11 52 33](https://github.com/hunyadi/md2conf/assets/102521188/67d49b63-033f-4c32-be25-48239893e5b9)
(the markdown code you provide)

Ok so it seems the markdown version I have doesn't work with code blocks, which one are you using? Any other library that could affect? Mine is:
Markdown           3.4.4

**Comment by hunyadi** [comment]
I have the following Python packages installed that are dependencies for *md2conf*:
* lxml 4.9.3
* Markdown 3.4.4
* pymdown-extensions 10.2
* requests 2.31.0

I am no Confluence expert but the Confluence version might also have a say in how the content is displayed. Identical [Confluence Storage Format](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) documents might be rendered differently in versions of Confluence.

**Comment by albertocarrf** [comment]
We have Confluence cloud, I will check the version and I will let you know

**Comment by albertocarrf** [comment]
I'm doing some tests and it seems code blocks with `` , cursive with ** and items in unordered lists add a new line every time you set a character:
-----------------------
- item 
translates into: 
- 
   item
-----------------------
*cursive*
translates into:
(new line)
cursive text
(newline)
-----------------------
`code block`
translates into:
(new line)
code blocked
(new line)
-----------------------


![Captura de pantalla 2023-08-30 a las 12 35 18](https://github.com/hunyadi/md2conf/assets/102521188/6f566d03-26be-4ac1-bfaf-2fe0a1c81f0f)
![Captura de pantalla 2023-08-30 a las 12 35 00](https://github.com/hunyadi/md2conf/assets/102521188/f4126329-17bc-406d-ad67-4e2d31984a95)

Confluence version:
Confluence 1000.0.0-732f22cda01f

**Comment by hunyadi** [comment]
I will add debugging features to *md2conf* to save the generated Confluence Storage Format (CSF) document before it is uploaded to Confluence. This would help us pin down the issue and tell if it's related to how the Python package *markdown* parses the Markdown document, or to how Confluence understands the uploaded CSF document.

**Comment by hunyadi** [comment]
Since the latest commit to branch `master`, *md2conf* would print the generated Confluence Storage Format document in debug mode:

```
python3 -m md2conf --loglevel=debug sample/example.md
```

If you can share the Markdown source document and log output, we can track down what the likely root cause of the formatting error is.
