### ISSUE TITLE
warning and notes appear to render incorrectly

### ISSUE THREAD

**Issue by joes-myob** [hunyadi/md2conf#25]
I just published a test page

```
!!! info "optional explicit title within double quotes"
    Any number of other indented markdown elements.

    This is the second paragraph.

!!! warning
    You should note that the title will be automatically capitalized.

!!! tip
    You should note that the title will be automatically capitalized.

!!! note
    "Don't try this at home"
    ...
```

Appears to render in confluence as 

![image](https://github.com/hunyadi/md2conf/assets/92417014/734c1dfc-e011-4db3-925c-e186583d5327)

I'd expect the note to render as 
![image](https://github.com/hunyadi/md2conf/assets/92417014/d37f0d33-b28a-4bbc-a765-43e816b019cc)

warning to be 
![image](https://github.com/hunyadi/md2conf/assets/92417014/01eb6f80-dbab-4964-ac8c-c767602d4fff)

And error to be
![image](https://github.com/hunyadi/md2conf/assets/92417014/364933cd-5b39-4e1b-a742-39366aeebdd5)

**Comment by hunyadi** [comment]
Unfortunately, I am no expert in Confluence. The utility *md2conf* translates Markdown admonitions `info`, `tip`, `note` and `warning` into Confluence`structured-macro` instances of the same `name` attribute. Specifically, the `note` macro gets the exclamation mark in a triangle, and the `warning` macro gets the X in a circle. This is how these get rendered by our managed Confluence:

![admonitions](https://github.com/hunyadi/md2conf/assets/7794010/e91e1361-1bbd-43f0-9aef-48689ea3dadf)

This is the Markdown source for the above image:

```
!!! info
    This is an information panel.

!!! info "Optional explicit title"
    This is an information panel with an explicit title.

    This is the second paragraph.

!!! tip "Tip of the day"
    This is a structured macro panel showing a tip.

!!! note "A note"
    This is a structured macro panel showing a note.

!!! warning "A warning message"
    This is a structured macro panel showing a warning.
```

The strange rendering for "optional explicit title within double quotes" in your case might be attributable to a less recent version of *Python-Markdown*. Does it help if you update dependencies?

```
python3 -m pip install --upgrade markdown types-markdown pymdown-extensions
```

**Comment by joes-myob** [comment]
Thanks for the reply
Tried updating the dependencies - seems like a similar result. 

Will close this issue. thanks
