### ISSUE TITLE
Ignore parts of the markdown

### ISSUE THREAD

**Issue by benmathews** [hunyadi/md2conf#28]
I'm trying to create presentations using https://marp.app/ and then publish them into confluence using md2conf. Everything works well except Marp uses [frontmatter](https://marpit.marp.app/directives?id=front-matter) to contain meta information. ([See also](https://jekyllrb.com/docs/front-matter/)) 

Is it possible to drop the frontmatter?

**Comment by hunyadi** [comment]
A change has been pushed to the branch `master`, which ignores frontmatter in Markdown sources.

**Comment by benmathews** [comment]
Works great. Thank you.
