### ISSUE TITLE
Feature Request: Support for `<details><summary>` block

### ISSUE THREAD

**Issue by zender-vivodyne** [hunyadi/md2conf#45]
# Usecase

We are using markdown in Github to support collapsible sections. See [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections). Would like that to be converted into a Confluence `Expand Macro`

<img width="811" alt="image" src="https://github.com/user-attachments/assets/90b9d1b5-7478-4818-8bc8-27a346312387">

# Issues

Noticed today that the `markdown` python library doesn't seemingly parse things correctly when inside the `details/summary` blocks. For example if you nest a markdown list inside `details` it doesn't run it into a `<ul><li>`. Unsure if this issue is 2 things or not. 

1. PR into markdown to handle the `details/summary` blocks better so that html is returned correctly
2. PR here to turn any `details/summary` blocks into Confluence `Expand Macros`

Likely they are not dependent but would likely want both for to have correctly rendered data.

**Comment by zendern** [comment]
On issue 1. above i did open this on the markdown library side as well. https://github.com/Python-Markdown/markdown/issues/1478

**Comment by zendern** [comment]
> On issue 1. above i did open this on the markdown library side as well. [Python-Markdown/markdown#1478](https://github.com/Python-Markdown/markdown/issues/1478)

Looks like there is a plugin available to support this. I'll look at PR'ing this change should be simple enough. https://github.com/Python-Markdown/markdown/issues/1478#issuecomment-2318383029. That at least gets the first part of this to work. And then just need to figure out the confluence conversion part.

**Comment by hunyadi** [comment]
This has been implemented on the `master` branch: *Add support for collapsed sections with expand macro*.

**Comment by zendern** [comment]
> This has been implemented on the `master` branch: *Add support for collapsed sections with expand macro*.

@hunyadi thanks for turning around this feature so quickly. I did some testing on my docs and it worked mostly. I just opened #49 to fix one issue I found. Would love to see a new release soon. Let me know if I can help out in any other ways.
