### ISSUE TITLE
md2conf is looking for a local file when attachment page is a http url to an image in GitHub

### ISSUE THREAD

**Issue by golharam** [hunyadi/md2conf#47]

**Comment by hunyadi** [comment]
Let me re-phrase to check if I understand the issue report correctly.

You are looking for a mechanism to embed a remote image in a Confluence wiki page specified with an absolute URL to an image hosted in GitHub, e.g.

```
![Remote PNG image](https://github.com/hunyadi/md2conf/blob/master/sample/figure/interoperability.png)
```

To the best of my knowledge, Confluence doesn't let you add a remote image to a Confluence page directly, though workarounds may exist.

**Comment by golharam** [comment]
Apologies, I was writing this quickly as I was working on this...let's me clarify...

We have a GitHub repo with a README.md file.  In the file, there are images that are embedded as either https urls to GitHub user content (uploaded images) or artifacts of the build process.

When I run md2conf, the script sees the url, but thinks its a local file, instead of treating it as an https url.  

I believe the script should download the file first.

**Comment by hunyadi** [comment]
From a convenience point of view, this makes sense. *md2conf* could use the Python library `requests` to download the files to the local system first, and then upload them to Confluence as attachments. However, we need to mitigate the risks of downloading potentially malicious content, as well as any authentication that the URL might require (e.g. *md2conf* would need to be "logged in" to GitHub if it's a private repository).

**Comment by golharam** [comment]
I discovered some of the user content images are not accessible via anonymous (not logged in) users, and as such this wouldn't work.  We had to move the images to be part of the GitHub repo.
