### ISSUE TITLE
Support for Github style alerts

### ISSUE THREAD

**Issue by zendern** [hunyadi/md2conf#50]
### Feature Request:

Github has support for the following style of alerts. https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

When used today they end up looking like this in Confluence. 

<img width="799" alt="image" src="https://github.com/user-attachments/assets/f2556e0b-84aa-4f38-99c2-8fbe40538252">

But should end up looking like this

<img width="1214" alt="Screenshot 2024-09-06 at 8 48 14 AM" src="https://github.com/user-attachments/assets/64e87fb9-a5be-4660-9d0a-3317a3a50c32">

## Details

Github alerts mapped to Confluence panels

| Github | Confluence |
| --- | -- |
| NOTE | Note |
| TIP |  Info or maybe Success (Tip is green on Github side so maybe Success?) |
| IMPORTANT | Info or maybe Success  |
| WARNING |  Warning |
| CAUTION | Error |

### Potential Solution:

Figure out a way to convert to [Admonitions](https://python-markdown.github.io/extensions/admonition/) might make sense so its consistent. But also could be its own code path.

**Comment by hunyadi** [comment]
This has been implemented on the `master` branch: *Add support for GitHub syntax of alerts/admonitions*.
