### ISSUE TITLE
Add version details to help or a new --version flag

### ISSUE THREAD

**Issue by zendern** [hunyadi/md2conf#52]
Most cli tools have a way to check the version you are running. I just upgraded to 0.2.0 and wanted to double check and realized there was no way i could do that.

**Comment by hunyadi** [comment]
The package sets the standard Python package tag `__version__` in `__init__.py`, i.e. you can print the current version with the following:
```
python3 -c "import md2conf; print(md2conf.__version__)"
```
However, I agree a `--version` switch is more user-friendly.

**Comment by hunyadi** [comment]
The command line option `--version` has been implemented. The latest commit on the branch `master` prints the version number (set in `__init__.py`) to the standard output and quits, similarly to how most Linux command-line tools do.
