### ISSUE TITLE
Support Gitlab alert box markdown

### ISSUE THREAD

**Issue by adongy** [hunyadi/md2conf#56]
Hello,

Recently support for Github flavored markdown alert boxes was added.

Gitlab has its own version of it, so I'd like to request to add their regexes too, however I understand this is opening a new can of worms of whether both Github and Gitlab features should be added or not.

https://docs.gitlab.com/ee/development/documentation/styleguide/#alert-boxes

Thanks.

**Comment by hunyadi** [comment]
`FLAG:`, `NOTE:`, `WARNING:` and `DISCLAIMER:` are now recognized as prefixes in blockquote text that indicate a GitLab alert box, and are transformed into a Confluence structured macros *info*, *tip*, *note*, or *warning*.
