### ISSUE TITLE
Unable to pull `hunyadi/md2conf:latest` container image

### ISSUE THREAD

**Issue by kedoodle** [hunyadi/md2conf#60]
Hi there, it seems as though the `hunyadi/md2conf` container repository is not available for public pulls:
```console
$ docker pull hunyadi/md2conf:latest
Error response from daemon: pull access denied for hunyadi/md2conf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by hunyadi** [comment]
I have overhauled `Dockerfile` and updated several `*.py` sources to properly support `@mermaid-js/mermaid-cli` such that *md2conf* works in Docker even when Mermaid diagrams are involved. The following commands now execute without error on the branch `dev`:

```
docker build -f Dockerfile -t md2conf-image .
docker run -i -t --rm --env-file .env --name md2conf -v $(pwd):/data md2conf-image sample/index.md --ignore-invalid-url
```

Can you confirm they work in your environment as you expect? Thanks in advance!

**Comment by kedoodle** [comment]
Hey @hunyadi, thank you! Looks to be working on my machine `--local`.
