### ISSUE TITLE
Local anchor links not working correctly in Confluence

### ISSUE THREAD

**Issue by erauner12** [hunyadi/md2conf#64]
When converting Markdown documents with local anchor links to Confluence pages using md2conf, the generated links are not functioning as expected. The links are being created as web links instead of Confluence's advanced links, causing navigation issues within the page I think?

Steps to reproduce:
1. Create a Markdown file with a table of contents and corresponding section headers.
2. Include local anchor links in the table of contents (e.g., `[Section Title](#section-title)`).
3. Convert the Markdown file 
4. Publish the converted content to a Confluence page.

Expected behavior:
Clicking on a local anchor link in the table of contents should navigate to the corresponding section within the same Confluence page.

Actual behavior:
Clicking on a local anchor link either refreshes the page or does not navigate to the intended section. The links are being created as "web links" instead of Confluence's advanced links

ex: 
<img width="771" alt="image" src="https://github.com/user-attachments/assets/4089ec4f-7644-42e7-8862-eea6b6226a22">

Workaround:
After publishing the page to Confluence, manually editing each link and changing it to an "Advanced" link in the Confluence editor fixes the issue. This suggests that the problem lies in how md2conf is generating the links.

<img width="771" alt="image" src="https://github.com/user-attachments/assets/ad296f40-7c36-4130-b43e-401892443a68">

```
      - [Backend-Only Deployment](#backend-only-deployment)
...
      - [Arbitrary Order Change](#arbitrary-order-change)
```
- this is the one I have been testing against: `arbitrary-order-change`

```
#### Arbitrary Order Change
<text>
```

**Comment by erauner12** [comment]
Interesting:

`https://<redacted>/pages/viewpage.action?pageId=223753291#arbitrary-order-change`

vs:

`https://<redacted>/display/PROVNG/express_deployment_scenarios#express_deployment_scenarios-arbitrary-order-change`

It seems when I change it to advanced, this is what changes if you copy the link address

**Comment by erauner12** [comment]
As nice as as github links are I think just regular old table of contents macro would do the trick too. hmm might try this

**Comment by hunyadi** [comment]
From what I saw in Confluence Storage Format (CSF), simple links are HTML anchor elements (`<a href="...">`), whereas advanced links are so-called `structured-macro` instances. *md2conf* already uses the `structured-macro` variant for generating anchor targets for headings. This is enabled with the command-line option `--heading-anchors`. This allows us to assign lowercase anchor names to headings (as in GitHub) as opposed to mixed-case anchor names (as in Confluence). Specifically, this has helped users with their Markdown table of contents. Perhaps you are missing `--heading-anchors` too?

**Comment by erauner12** [comment]
Well actually I was using the `--heading-anchors` so it ws not making since to me why it was not properly re-directing when I clicked it?

```
    if grep -q "confluence-page-id:" "$file"; then
        echo "Updating existing page: $file"
        $PYTHON_PATH -m md2conf "$file" \
            --heading-anchors \
            -s "${CONFLUENCE_SPACE_KEY}" \
            -d "${CONFLUENCE_DOMAIN}" \
            -p "${CONFLUENCE_PATH}" \
            -a "${CONFLUENCE_API_KEY}" \
            --generated-by "This page was automatically generated" \
            --ignore-invalid-url \
            --render-mermaid \
            --loglevel debug
```

**Comment by hunyadi** [comment]
Local references within a Markdown document (i.e. URLs that consist of a *fragment* part only) are now expanded into Confluence advanced links:
```
<ac:link ac:anchor="anchor">
  <ac:link-body>
    ...
  </ac:link-body>
</ac:link>
```
This is activated with `--heading-anchors`. Links must use standard Markdown conversion rules to reference section headings (all lowercase).

Changes have been pushed to `master` with the commit text *Expand references within document to Confluence advanced links*.

**Comment by hunyadi** [comment]
Without `--heading-anchors`, *md2conf* doesn't touch link URLs, it pushes whatever local reference it finds to Confluence. Unfortunately, Markdown and Confluence don't have the same idea of how to generate an anchor from a heading, which means that your links will typically either work in standard Markdown viewers (or GitHub, or GitLab) but not in Confluence, or vice versa. This is where `--heading-anchors` comes in. First, it uses GitHub's mechanism to generate an anchor target ID from title text, as implemented in the Python function `title_to_identifier`. Next, it creates a Confluence anchor (Confluence Storage Format `<ac:link ac:anchor="anchor">...</ac:link>`) close to the heading such that links can refer to it. Finally, if links use one of the reference styles, either the Confluence auto-generated target, or the explicit `ac:link` should match.

I am glad to look at the problem in more depth but can you open a new issue such that we don't ping the original reporter while we are working on a resolution? Thank you in advance!
