### ISSUE TITLE
Support for excerpt marco

### ISSUE THREAD

**Issue by mroelandts** [hunyadi/md2conf#67]
Would it be possible to implement support for the excerpt macro?
-> https://confluence.atlassian.com/doc/excerpt-macro-148062.html

This way you can have generated confluence pages with content (example a summary) that you can link in other (non-generated) pages that will be updated automatically.
Inside the markdown we could mark the excerpt by using a markdown comment? (it's just a suggestion)

**Comment by hunyadi** [comment]
I am not sure. Strictly speaking, it would be possible. However, so far, *md2conf* has focused on making sure content that looks great in (standard) Markdown is published without loss of (textual or visual) information to Confluence. This feature request aims at bringing a Confluence feature into Markdown, which seems a little out of scope for *md2conf*.

**Comment by KarstenSiemer** [comment]
I could also use that functionality. Though, I have to say that I feel like @hunyadi is correct.
On the other hand, creating pages also is not part of markdown.
I'll check how to do something like that somehow else :-)
