### ISSUE TITLE
Update Confluence page title

### ISSUE THREAD

**Issue by LeTuR** [hunyadi/md2conf#73]
As a user I would like to be able to update a confluence page title via the front matter yaml:
```markdown
---
title: My Update Page Name
---
<!-- confluence-page-id: PAGE-ID -->
<!-- confluence-space-key: SPACE-KEY -->
# My Doc

Hello Doc
```

(We consider generation of a directory using `-r` to specify a root page id)

Current behavior:
- if `confluence-page-id` does not exist:
   - both `<!-- confluence-page-id: PAGE-ID -->` and `<!-- confluence-space-key: SPACE-KEY -->` are added to the begging of a file
   - front matter `title` value is used to create a new page but gets deleted
-  if `confluence-page-id` exists:
   -  both `<!-- confluence-page-id: PAGE-ID -->` and `<!-- confluence-space-key: SPACE-KEY -->` are kept
   - front matter `title` value is NOT used to create a new page

Expected behavior:
- if `confluence-page-id` does not exist:
   - both `<!-- confluence-page-id: PAGE-ID -->` and `<!-- confluence-space-key: SPACE-KEY -->` are added to the begging of a file after front-matter content
   - front matter `title` value is used to create a new page and is NOT deleted
-  if `confluence-page-id` exists:
   -  both `<!-- confluence-page-id: PAGE-ID -->` and `<!-- confluence-space-key: SPACE-KEY -->` are kept
   - front matter `title` value is used to update page title

**Comment by hunyadi** [comment]
Both issues are now covered by the commit *Use front-matter title to set Confluence page title* pushed to the branch `master`.
