### ISSUE TITLE
Resize image

### ISSUE THREAD

**Issue by kpallade** [hunyadi/md2conf#74]
Hello,

I'm trying to resize an images but I don't find the right way to do it.

What I've tried in my markdown file:

```
![Google Logo](google_logo.png){ height=20% }
```

```
<img src="google_logo.png" alt="Google Logo" height="50" />
```

In any case, the image appears in Confluence (I've uploaded it manually), but it is not resized.

Many thanks for your help

**Comment by hunyadi** [comment]
*md2conf* uses [Python-Markdown](https://python-markdown.github.io/) for converting Markdown to HTML (or, to be more precise, Confluence Storage Format, which is a variant of XHTML). Does Python-Markdown understand the seemingly non-standard syntax with the image height set in curly braces?

The `ac:image` macro to [embed an attached or external image](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html#ConfluenceStorageFormat-Images) has attributes `ac:height` and `ac:width`. (We already use `ac:align`.) We could populate these attributes based on attributes the source image has.

**Comment by hunyadi** [comment]
Linking to images hosted externally via a full URL is now possible with either of the following syntaxes:
```
![External image](http://confluence.atlassian.com/images/logo/confluence_48_trans.png)

<img src="http://confluence.atlassian.com/images/logo/confluence_48_trans.png" width="24" height="24" />
```
The latter syntax allows you to specify image size.

**Comment by kpallade** [comment]
I wil try it, thank you very much :)

**Comment by cth35** [comment]
Hello, is it possible to have a width in percentage ?
Like : 
`<img src="./img/A1.png" alt="A1" style="width: 60%;" />`
There is no error when writting like this but it seems width is not taken into account.

**Comment by cth35** [comment]
Ok, no problem. Thank you very much for your quick investigations.
