### ISSUE TITLE
Relative links not working in On-prem confluence

### ISSUE THREAD

**Issue by matt-land** [hunyadi/md2conf#75]
I have an on-prem version of Confluence.
The version info is:
```
<meta name="ajs-version-number" content="8.8.0">
<meta name="ajs-build-number" content="9103">
```
It is the February 2024 Release, so its currently not ancient.

I have 2 pages published using md2conf (Via Docker) in a space called OURSPACE:
```
- README.md <!-- confluence-page-id: 231542343 --> <!-- confluence-space-key: OURSPACE -->
- Common Examples.md <!-- confluence-page-id: 231543609 --> <!-- confluence-space-key: OURSPACE -->
```
Both files are in a folder together. Each one links to the other using relative urls, like so:
```
# README.md links to Common Examples.md
[Common Examples](./Common Examples.md)

# Common Examples.md links to README.md
[README.md](./README.md)
```

The urls after publishing to confluence resolve to:
```
# In the README.md confluence page, trying to link to Common Examples
https://somecorp.com/spaces/OURSPACE/pages/231543609/Common%20Examples

# In the Common Examples confluence page, trying to link to README
https://somecorp.com/spaces/OURSPACE/pages/231542343/README
```

These do not work.
<img width="642" alt="Screenshot 2024-12-17 at 2 16 36 PM" src="https://github.com/user-attachments/assets/dc9abef5-dd8b-44ef-925e-a8e30309a4cd" />

I would expect the links to be in this format instead:
```
https://somecorp.com/pages/viewpage.action?pageId=231542343
https://somecorp.com/pages/viewpage.action?pageId=231543609
```

Any recommendations?
I can swap to external URLs but I'd prefer to get relative links working since they get evaluated at publish time, preventing errors.

**Comment by hunyadi** [comment]
As it appears, you might be looking for the command-line switch `--webui-links`. This produces URLs of the following format:
```
BASE_PATH/pages/viewpage.action?pageId=PAGE_ID
```

**Comment by hunyadi** [comment]
The documentation has been updated to suggest using the command-line switch `--webui-links` for an on-prem edition of Confluence.
