### ISSUE TITLE
json code block fails to publish

### ISSUE THREAD

**Issue by matt-land** [hunyadi/md2conf#76]
I have an on-prem version of Confluence.
The version info is:
```
<meta name="ajs-version-number" content="8.8.0">
<meta name="ajs-build-number" content="9103">
```

I copied the json block sample from https://github.com/hunyadi/md2conf/blob/master/sample/code.md?plain=1#L73

```json
{
  "boolean": true,
  "integer": 42,
  "string": "value",
  "list": [1,2,3]
}
```

At publish time, there are no errors.

In Confluence it appears as:
<img width="867" alt="Screenshot 2024-12-17 at 3 12 09 PM" src="https://github.com/user-attachments/assets/c09f855f-6b94-405d-94b9-f1f900d2f373" />

Is this an issue with my version of Confluence?

**Comment by hunyadi** [comment]
Hard to tell what could be going on, I am afraid. Internally, the above JSON block would translate into the following Confluence Storage Format XHTML:
```xhtml
<ac:structured-macro ac:name="code" ac:schema-version="1">
  <ac:parameter ac:name="theme">Midnight</ac:parameter>
  <ac:parameter ac:name="language">json</ac:parameter>
  <ac:parameter ac:name="linenumbers">true</ac:parameter>
  <ac:plain-text-body><![CDATA[{
    "boolean": true,
    "integer": 42,
    "string": "value",
    "list": [1,2,3]
}]]></ac:plain-text-body>
```
Perhaps your version of Confluence doesn't understand one of the `ac:parameter` values? Can you try removing one or more of these, and see if that solves the issue?

**Comment by matt-land** [comment]
I don't think it's the theme. It's specific to using the 'json' code block. I will try more code blocks and report back

<img width="449" alt="Screenshot 2024-12-17 at 4 26 34 PM" src="https://github.com/user-attachments/assets/a83ce2fe-32ce-4394-90a3-85c5512dce3d" />

**Comment by matt-land** [comment]
I took the contents of the samples page and published all except Tex.

- [X] (bare)
- [X] C
- [X] C++
- [X] CSS
- [ ] Go "Error rendering macro 'code': Invalid value specified for parameter '[Ljava.lang.Object;@d5ced1d'"
- [X] HTML
- [X] Java
- [ ] Kotlin "Error rendering macro 'code': Invalid value specified for parameter '[Ljava.lang.Object;@cdf34ee'"
- [ ] Objective-C "Error rendering macro 'code': Invalid value specified for parameter '[Ljava.lang.Object;@17812083'"
- [X] Python
- [X] Ruby
- [ ] Rust "Error rendering macro 'code': Invalid value specified for parameter '[Ljava.lang.Object;@2523e3ad'"
- [ ] Swift "Error rendering macro 'code': Invalid value specified for parameter '[Ljava.lang.Object;@3962b682'"

The memory addresses do not seem to matter, since they mutate on re-publish. The languages that fail each time remain constant.

**Comment by hunyadi** [comment]
Your environment might not support all the languages showcased in the *md2conf* test set. For example, the Confluence [documentation for the code block macro](https://support.atlassian.com/confluence-cloud/docs/insert-the-code-block-macro/) has fewer and/or different languages than included in the test set:
* ActionScript
* AppleScript
* Bash
* C#
* C++
* CSS
* ColdFusion
* Delphi
* Diff
* Erlang
* Groovy
* HTML and XML
* Java
* Java FX
* JavaScript
* Plain Text
* PowerShell
* Python
* Ruby
* SQL
* Sass
* Scala
* Visual Basic

**Comment by hunyadi** [comment]
It appears there is variation in what languages each version of Confluence supports for the code block macro. Even though all of the languages showcased on the demo page work in our managed Confluence environment (and honor the syntax highlighting specific to the language), you might encounter errors with other editions of Confluence.
